-- Scooters Table with ID as Primary Key
CREATE TABLE ES.SCOOTERS(
    ID VARCHAR(10) NOT NULL,
    NAME VARCHAR(15) NOT NULL,
    CITY VARCHAR(20) NOT NULL,
    MODEL VARCHAR(15) NOT NULL,
    battery_capacity VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID));

-- Customer Table with ID as Primary Key
CREATE TABLE ES.CUSTOMER(
    ID VARCHAR(10) NOT NULL,
    NAME VARCHAR(15) NOT NULL,
    PLATFORM_TOKEN VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID));

-- Rental Reservations table with scooter_id and customer_id as foriegn key
CREATE TABLE ES.RENTAL_RESERVATIONS(
    SCOOTER_ID VARCHAR(10) REFERENCES ES.SCOOTERS(ID),
    CUSTOMER_ID VARCHAR(10) REFERENCES ES.CUSTOMER(ID),
    START_DATETIME TIMESTAMP,
    END_DATETIME TIMESTAMP);